/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import java.awt.BorderLayout;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;



/**
 *
 * @author Estudiante
 */
public class MainWindow extends javax.swing.JFrame {
    MainPanel panel;
    int id_areaasignada;
    /**
     * Creates new form MainWindow
     */
    public MainWindow(int id_areaasignada) {
        this.id_areaasignada=id_areaasignada;
        initComponents();
    }

    public void setPanel()
    {
        panel=new MainPanel(id_areaasignada);
        this.add(panel,BorderLayout.CENTER);
        this.setSize(1200,900);
        this.repaint();
        /*
     //   Icon imageIcon = new ImageIcon(getClass().getResource("images/imagen.jpg"));
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("images/imagen.jpg"));
        
        // Crear un JLabel y establecer el icono de imagen
        JLabel label = new JLabel(imageIcon);
        label.setSize(100, 100);
        label.setIcon(imageIcon);
        label.setText("hola /n ?\n salta la linea??");
        // Crear un JPanel
        JPanel panel = new JPanel();
        
        // Agregar el JLabel al JPanel
        panel.add(label);
        
        // Crear un JFrame y configurar el layout y el cierre
       
        this.setLayout(new BorderLayout());
        //this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Agregar el JPanel al JFrame
        this.add(panel, BorderLayout.CENTER);

        // Ajustar el tamaño del JFrame y hacerlo visible
        this.setSize(300, 300);
        this.setVisible(true);*/
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1168, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
